name: QA Automation Pipeline

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  api-tests:
    name: API Tests - Swagger Petstore
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes de API
        run: pytest api_tests/tests -m api --html=reports/api-report.html --self-contained-html

      - name: Publicar relatório API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: reports/api-report.html

  web-tests:
    name: Web Tests - SauceDemo
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar testes Web
        env:
          HEADLESS: "true"
        run: pytest web_tests/tests -m web --html=reports/web-report.html --self-contained-html

      - name: Publicar relatório Web
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-report
          path: reports/web-report.html
